name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zul'
      - name: Build with Maven
        run: mvn clean install
      - name: Upload core package artifact
        uses: actions/upload-artifact@v2
        with:
          path: coretarget/*.jar
